#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-NetPacket
Version  : 1.6.0
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/Y/YA/YANICK/NetPacket-1.6.0.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/Y/YA/YANICK/NetPacket-1.6.0.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libn/libnetpacket-perl/libnetpacket-perl_1.6.0-1.debian.tar.xz
Summary  : 'assemble/disassemble network packets at the protocol level'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-NetPacket-license
Requires: perl-NetPacket-man

%description
NAME
NetPacket - assemble/disassemble network packets at the protocol level
VERSION
version 1.6.0

%package license
Summary: license components for the perl-NetPacket package.
Group: Default

%description license
license components for the perl-NetPacket package.


%package man
Summary: man components for the perl-NetPacket package.
Group: Default

%description man
man components for the perl-NetPacket package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n NetPacket-1.6.0
mkdir -p %{_topdir}/BUILD/NetPacket-1.6.0/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/NetPacket-1.6.0/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-NetPacket
cp LICENSE %{buildroot}/usr/share/doc/perl-NetPacket/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-NetPacket/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/NetPacket.pm
/usr/lib/perl5/site_perl/5.26.1/NetPacket/ARP.pm
/usr/lib/perl5/site_perl/5.26.1/NetPacket/Ethernet.pm
/usr/lib/perl5/site_perl/5.26.1/NetPacket/ICMP.pm
/usr/lib/perl5/site_perl/5.26.1/NetPacket/IGMP.pm
/usr/lib/perl5/site_perl/5.26.1/NetPacket/IP.pm
/usr/lib/perl5/site_perl/5.26.1/NetPacket/IPX.pm
/usr/lib/perl5/site_perl/5.26.1/NetPacket/TCP.pm
/usr/lib/perl5/site_perl/5.26.1/NetPacket/UDP.pm
/usr/lib/perl5/site_perl/5.26.1/NetPacket/USBMon.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-NetPacket/LICENSE
/usr/share/doc/perl-NetPacket/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/NetPacket.3
/usr/share/man/man3/NetPacket::ARP.3
/usr/share/man/man3/NetPacket::Ethernet.3
/usr/share/man/man3/NetPacket::ICMP.3
/usr/share/man/man3/NetPacket::IGMP.3
/usr/share/man/man3/NetPacket::IP.3
/usr/share/man/man3/NetPacket::IPX.3
/usr/share/man/man3/NetPacket::TCP.3
/usr/share/man/man3/NetPacket::UDP.3
/usr/share/man/man3/NetPacket::USBMon.3
